classDiagram
    class infra {
        +module
        +files: 5
    }
    class nix {
        +module
        +files: 5
    }
    class sdks {
        +module
        +files: 3
    }
    class script {
        +module
        +files: 8
    }
    class github {
        +module
        +files: 2
    }
    class packages {
        +module
        +files: 20
    }